import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/enhanced_medicine.dart';
import '../models/medicine_log.dart';

/// One medicine + its logs for the report.
class MedicineReportEntry {
  final EnhancedMedicine medicine;
  final List<MedicineLog> logs;
  const MedicineReportEntry({required this.medicine, required this.logs});
}

/// Builds a clinician-shareable medication-adherence PDF from the user's own
/// logs — a doctor-visit export (the headline feature of apps like MyTherapy).
/// Pure Dart (the `pdf` package needs no Flutter bindings), so the document can
/// be built and unit-tested headlessly; the UI shares it via `printing`.
class AdherenceReportService {
  const AdherenceReportService._();

  static Future<Uint8List> buildPdf({
    required List<MedicineReportEntry> entries,
    DateTime? from,
    DateTime? to,
    String? patientName,
    DateTime? generatedAt,
  }) async {
    final doc = pw.Document();
    final now = generatedAt ?? DateTime.now();

    // Overall adherence across all entries in the (optional) window.
    var totalDue = 0, totalTaken = 0;
    final rows = <List<String>>[];
    for (final e in entries) {
      final logs = _inWindow(e.logs, from, to);
      final taken = logs.where((l) => l.isTaken).length;
      final missed = logs.where((l) => l.isMissed).length;
      final skipped = logs.where((l) => l.isSkipped).length;
      final due = taken + missed + skipped; // pending doesn't count as due yet
      totalDue += due;
      totalTaken += taken;
      final pct = due > 0 ? (taken / due * 100).round() : 0;
      rows.add([
        _medLabel(e.medicine),
        e.medicine.schedule.frequencyDescription,
        due > 0 ? '$pct%' : '-',
        '$taken',
        '$missed',
        '$skipped',
      ]);
    }
    final overall = totalDue > 0 ? (totalTaken / totalDue * 100).round() : 0;

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(40, 44, 40, 44),
        build: (context) => [
          _header(patientName, from, to, now),
          pw.SizedBox(height: 18),
          _summary(overall, totalTaken, totalDue),
          pw.SizedBox(height: 20),
          pw.Text('Per-medication adherence',
              style: pw.TextStyle(fontSize: 13, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          _table(rows),
          pw.SizedBox(height: 24),
          pw.Text(
            'Adherence = doses marked taken / doses due (taken + missed + skipped) '
            "over the selected period. Generated by DailyMinder from the patient's "
            'self-reported logs; for clinical discussion only.',
            style: const pw.TextStyle(fontSize: 8.5, color: PdfColors.grey600),
          ),
        ],
      ),
    );
    return doc.save();
  }

  /// A per-dose CSV (Date,Time,Medicine,Status) — a spreadsheet-friendly export
  /// for the user or their doctor/caregiver. Pure Dart, on-device.
  static String buildCsv({
    required List<MedicineReportEntry> entries,
    DateTime? from,
    DateTime? to,
  }) {
    final rows = <List<String>>[];
    for (final e in entries) {
      for (final l in _inWindow(e.logs, from, to)) {
        final t = l.scheduledTime;
        final date = '${t.year}-${_2(t.month)}-${_2(t.day)}';
        final time = '${_2(t.hour)}:${_2(t.minute)}';
        final status = l.isTaken
            ? 'Taken'
            : l.isMissed
                ? 'Missed'
                : l.isSkipped
                    ? 'Skipped'
                    : 'Pending';
        rows.add([date, time, _medLabel(e.medicine), status]);
      }
    }
    rows.sort((a, b) {
      final d = a[0].compareTo(b[0]);
      return d != 0 ? d : a[1].compareTo(b[1]);
    });
    final buf = StringBuffer('Date,Time,Medicine,Status\n');
    for (final r in rows) {
      buf.writeln(r.map(_csvField).join(','));
    }
    return buf.toString();
  }

  static String _csvField(String s) =>
      (s.contains(',') || s.contains('"') || s.contains('\n'))
          ? '"${s.replaceAll('"', '""')}"'
          : s;

  static List<MedicineLog> _inWindow(
      List<MedicineLog> logs, DateTime? from, DateTime? to) {
    return logs.where((l) {
      final t = l.scheduledTime;
      if (from != null && t.isBefore(from)) return false;
      if (to != null && t.isAfter(to)) return false;
      return true;
    }).toList();
  }

  static String _medLabel(EnhancedMedicine m) {
    final strength =
        (m.strength != null && m.strength!.trim().isNotEmpty) ? ' ${m.strength}' : '';
    return '${m.name}$strength';
  }

  static pw.Widget _header(
      String? patient, DateTime? from, DateTime? to, DateTime now) {
    String fmt(DateTime d) =>
        '${d.year}-${_2(d.month)}-${_2(d.day)}';
    final range = (from != null && to != null)
        ? '${fmt(from)} to ${fmt(to)}'
        : 'All recorded doses';
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('Medication Adherence Report',
            style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 4),
        pw.Text('DailyMinder', style: const pw.TextStyle(fontSize: 11, color: PdfColors.teal700)),
        pw.SizedBox(height: 10),
        pw.Row(children: [
          if (patient != null && patient.trim().isNotEmpty)
            pw.Expanded(child: pw.Text('Patient: $patient', style: const pw.TextStyle(fontSize: 10))),
          pw.Expanded(child: pw.Text('Period: $range', style: const pw.TextStyle(fontSize: 10))),
          pw.Text('Generated: ${fmt(now)}', style: const pw.TextStyle(fontSize: 10)),
        ]),
        pw.SizedBox(height: 10),
        pw.Divider(color: PdfColors.grey400, thickness: .5),
      ],
    );
  }

  static pw.Widget _summary(int overall, int taken, int due) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        color: PdfColors.teal50,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.center,
        children: [
          pw.Text('$overall%',
              style: pw.TextStyle(
                  fontSize: 34, fontWeight: pw.FontWeight.bold, color: PdfColors.teal800)),
          pw.SizedBox(width: 14),
          pw.Column(crossAxisAlignment: pw.CrossAxisAlignment.start, children: [
            pw.Text('Overall adherence',
                style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
            pw.Text('$taken of $due scheduled doses taken',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700)),
          ]),
        ],
      ),
    );
  }

  static pw.Widget _table(List<List<String>> rows) {
    const headers = ['Medication', 'Schedule', 'Adherence', 'Taken', 'Missed', 'Skipped'];
    return pw.TableHelper.fromTextArray(
      headers: headers,
      data: rows,
      border: pw.TableBorder.all(color: PdfColors.grey300, width: .5),
      headerStyle: pw.TextStyle(fontSize: 9.5, fontWeight: pw.FontWeight.bold, color: PdfColors.white),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.teal600),
      cellStyle: const pw.TextStyle(fontSize: 9.5),
      cellAlignments: {
        0: pw.Alignment.centerLeft,
        1: pw.Alignment.centerLeft,
        2: pw.Alignment.center,
        3: pw.Alignment.center,
        4: pw.Alignment.center,
        5: pw.Alignment.center,
      },
      cellPadding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
    );
  }

  static String _2(int n) => n.toString().padLeft(2, '0');
}
